name: Python CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f "requirements.txt" ]; then pip install -r requirements.txt; fi
        pip install pytest pytest-html

    - name: Run tests
      run: |
        mkdir -p reports
        pytest --junitxml=reports/results.xml || true

    - name: Upload test results
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: reports/results.xml

   name: Send email notification
  if: always()
  uses: dawidd6/action-send-mail@v3
  with:
    server_address: smtp.gmail.com
    server_port: 465
    username: ${{ secrets.EMAIL_USERNAME }}
    password: ${{ secrets.EMAIL_PASSWORD }}
    from: Sapphire777.astro@gmail.com   # твоя пошта
    to: InsertYour@Mail.Here             # можна залишити свою або іншу
    subject: "Python CI Pipeline - ${{ github.repository }}"
    body: |
      Статус виконання workflow: ${{ job.status }}
      Build URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
    secure: true

